/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTasksRouteImport } from './routes/_public/tasks'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicSigninRouteImport } from './routes/_public/signin'
import { Route as PublicCustomersRouteImport } from './routes/_public/customers'
import { Route as PublicCreateTaskRouteImport } from './routes/_public/create-task'
import { Route as PublicCreateCustomerRouteImport } from './routes/_public/create-customer'
import { Route as ProtectedReportsRouteImport } from './routes/_protected/reports'
import { Route as ProtectedEmployeesRouteImport } from './routes/_protected/employees'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedCreateEmployeeRouteImport } from './routes/_protected/create-employee'
import { Route as PublicTasksTaskIdRouteImport } from './routes/_public/tasks.$taskId'
import { Route as PublicCustomersCustomerIdRouteImport } from './routes/_public/customers.$customerId'
import { Route as ProtectedEmployeesEmployeeIdRouteImport } from './routes/_protected/employees.$employeeId'
import { Route as PublicTasksTaskIdEditRouteImport } from './routes/_public/tasks.$taskId.edit'
import { Route as PublicCustomersCustomerIdEditRouteImport } from './routes/_public/customers.$customerId.edit'
import { Route as ProtectedEmployeesEmployeeIdEditRouteImport } from './routes/_protected/employees.$employeeId.edit'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicTasksRoute = PublicTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSigninRoute = PublicSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCustomersRoute = PublicCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCreateTaskRoute = PublicCreateTaskRouteImport.update({
  id: '/create-task',
  path: '/create-task',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCreateCustomerRoute = PublicCreateCustomerRouteImport.update({
  id: '/create-customer',
  path: '/create-customer',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ProtectedReportsRoute = ProtectedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedEmployeesRoute = ProtectedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedCreateEmployeeRoute = ProtectedCreateEmployeeRouteImport.update({
  id: '/create-employee',
  path: '/create-employee',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicTasksTaskIdRoute = PublicTasksTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => PublicTasksRoute,
} as any)
const PublicCustomersCustomerIdRoute =
  PublicCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => PublicCustomersRoute,
  } as any)
const ProtectedEmployeesEmployeeIdRoute =
  ProtectedEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => ProtectedEmployeesRoute,
  } as any)
const PublicTasksTaskIdEditRoute = PublicTasksTaskIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PublicTasksTaskIdRoute,
} as any)
const PublicCustomersCustomerIdEditRoute =
  PublicCustomersCustomerIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => PublicCustomersCustomerIdRoute,
  } as any)
const ProtectedEmployeesEmployeeIdEditRoute =
  ProtectedEmployeesEmployeeIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedEmployeesEmployeeIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/create-employee': typeof ProtectedCreateEmployeeRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/employees': typeof ProtectedEmployeesRouteWithChildren
  '/reports': typeof ProtectedReportsRoute
  '/create-customer': typeof PublicCreateCustomerRoute
  '/create-task': typeof PublicCreateTaskRoute
  '/customers': typeof PublicCustomersRouteWithChildren
  '/signin': typeof PublicSigninRoute
  '/signup': typeof PublicSignupRoute
  '/tasks': typeof PublicTasksRouteWithChildren
  '/employees/$employeeId': typeof ProtectedEmployeesEmployeeIdRouteWithChildren
  '/customers/$customerId': typeof PublicCustomersCustomerIdRouteWithChildren
  '/tasks/$taskId': typeof PublicTasksTaskIdRouteWithChildren
  '/employees/$employeeId/edit': typeof ProtectedEmployeesEmployeeIdEditRoute
  '/customers/$customerId/edit': typeof PublicCustomersCustomerIdEditRoute
  '/tasks/$taskId/edit': typeof PublicTasksTaskIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/create-employee': typeof ProtectedCreateEmployeeRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/employees': typeof ProtectedEmployeesRouteWithChildren
  '/reports': typeof ProtectedReportsRoute
  '/create-customer': typeof PublicCreateCustomerRoute
  '/create-task': typeof PublicCreateTaskRoute
  '/customers': typeof PublicCustomersRouteWithChildren
  '/signin': typeof PublicSigninRoute
  '/signup': typeof PublicSignupRoute
  '/tasks': typeof PublicTasksRouteWithChildren
  '/employees/$employeeId': typeof ProtectedEmployeesEmployeeIdRouteWithChildren
  '/customers/$customerId': typeof PublicCustomersCustomerIdRouteWithChildren
  '/tasks/$taskId': typeof PublicTasksTaskIdRouteWithChildren
  '/employees/$employeeId/edit': typeof ProtectedEmployeesEmployeeIdEditRoute
  '/customers/$customerId/edit': typeof PublicCustomersCustomerIdEditRoute
  '/tasks/$taskId/edit': typeof PublicTasksTaskIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_protected/create-employee': typeof ProtectedCreateEmployeeRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/employees': typeof ProtectedEmployeesRouteWithChildren
  '/_protected/reports': typeof ProtectedReportsRoute
  '/_public/create-customer': typeof PublicCreateCustomerRoute
  '/_public/create-task': typeof PublicCreateTaskRoute
  '/_public/customers': typeof PublicCustomersRouteWithChildren
  '/_public/signin': typeof PublicSigninRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_public/tasks': typeof PublicTasksRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_protected/employees/$employeeId': typeof ProtectedEmployeesEmployeeIdRouteWithChildren
  '/_public/customers/$customerId': typeof PublicCustomersCustomerIdRouteWithChildren
  '/_public/tasks/$taskId': typeof PublicTasksTaskIdRouteWithChildren
  '/_protected/employees/$employeeId/edit': typeof ProtectedEmployeesEmployeeIdEditRoute
  '/_public/customers/$customerId/edit': typeof PublicCustomersCustomerIdEditRoute
  '/_public/tasks/$taskId/edit': typeof PublicTasksTaskIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-employee'
    | '/dashboard'
    | '/employees'
    | '/reports'
    | '/create-customer'
    | '/create-task'
    | '/customers'
    | '/signin'
    | '/signup'
    | '/tasks'
    | '/employees/$employeeId'
    | '/customers/$customerId'
    | '/tasks/$taskId'
    | '/employees/$employeeId/edit'
    | '/customers/$customerId/edit'
    | '/tasks/$taskId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-employee'
    | '/dashboard'
    | '/employees'
    | '/reports'
    | '/create-customer'
    | '/create-task'
    | '/customers'
    | '/signin'
    | '/signup'
    | '/tasks'
    | '/employees/$employeeId'
    | '/customers/$customerId'
    | '/tasks/$taskId'
    | '/employees/$employeeId/edit'
    | '/customers/$customerId/edit'
    | '/tasks/$taskId/edit'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_protected/create-employee'
    | '/_protected/dashboard'
    | '/_protected/employees'
    | '/_protected/reports'
    | '/_public/create-customer'
    | '/_public/create-task'
    | '/_public/customers'
    | '/_public/signin'
    | '/_public/signup'
    | '/_public/tasks'
    | '/_public/'
    | '/_protected/employees/$employeeId'
    | '/_public/customers/$customerId'
    | '/_public/tasks/$taskId'
    | '/_protected/employees/$employeeId/edit'
    | '/_public/customers/$customerId/edit'
    | '/_public/tasks/$taskId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/tasks': {
      id: '/_public/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof PublicTasksRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/signin': {
      id: '/_public/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PublicSigninRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/customers': {
      id: '/_public/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof PublicCustomersRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/create-task': {
      id: '/_public/create-task'
      path: '/create-task'
      fullPath: '/create-task'
      preLoaderRoute: typeof PublicCreateTaskRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/create-customer': {
      id: '/_public/create-customer'
      path: '/create-customer'
      fullPath: '/create-customer'
      preLoaderRoute: typeof PublicCreateCustomerRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_protected/reports': {
      id: '/_protected/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ProtectedReportsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/employees': {
      id: '/_protected/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof ProtectedEmployeesRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/create-employee': {
      id: '/_protected/create-employee'
      path: '/create-employee'
      fullPath: '/create-employee'
      preLoaderRoute: typeof ProtectedCreateEmployeeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/tasks/$taskId': {
      id: '/_public/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/tasks/$taskId'
      preLoaderRoute: typeof PublicTasksTaskIdRouteImport
      parentRoute: typeof PublicTasksRoute
    }
    '/_public/customers/$customerId': {
      id: '/_public/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof PublicCustomersCustomerIdRouteImport
      parentRoute: typeof PublicCustomersRoute
    }
    '/_protected/employees/$employeeId': {
      id: '/_protected/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/employees/$employeeId'
      preLoaderRoute: typeof ProtectedEmployeesEmployeeIdRouteImport
      parentRoute: typeof ProtectedEmployeesRoute
    }
    '/_public/tasks/$taskId/edit': {
      id: '/_public/tasks/$taskId/edit'
      path: '/edit'
      fullPath: '/tasks/$taskId/edit'
      preLoaderRoute: typeof PublicTasksTaskIdEditRouteImport
      parentRoute: typeof PublicTasksTaskIdRoute
    }
    '/_public/customers/$customerId/edit': {
      id: '/_public/customers/$customerId/edit'
      path: '/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof PublicCustomersCustomerIdEditRouteImport
      parentRoute: typeof PublicCustomersCustomerIdRoute
    }
    '/_protected/employees/$employeeId/edit': {
      id: '/_protected/employees/$employeeId/edit'
      path: '/edit'
      fullPath: '/employees/$employeeId/edit'
      preLoaderRoute: typeof ProtectedEmployeesEmployeeIdEditRouteImport
      parentRoute: typeof ProtectedEmployeesEmployeeIdRoute
    }
  }
}

interface ProtectedEmployeesEmployeeIdRouteChildren {
  ProtectedEmployeesEmployeeIdEditRoute: typeof ProtectedEmployeesEmployeeIdEditRoute
}

const ProtectedEmployeesEmployeeIdRouteChildren: ProtectedEmployeesEmployeeIdRouteChildren =
  {
    ProtectedEmployeesEmployeeIdEditRoute:
      ProtectedEmployeesEmployeeIdEditRoute,
  }

const ProtectedEmployeesEmployeeIdRouteWithChildren =
  ProtectedEmployeesEmployeeIdRoute._addFileChildren(
    ProtectedEmployeesEmployeeIdRouteChildren,
  )

interface ProtectedEmployeesRouteChildren {
  ProtectedEmployeesEmployeeIdRoute: typeof ProtectedEmployeesEmployeeIdRouteWithChildren
}

const ProtectedEmployeesRouteChildren: ProtectedEmployeesRouteChildren = {
  ProtectedEmployeesEmployeeIdRoute:
    ProtectedEmployeesEmployeeIdRouteWithChildren,
}

const ProtectedEmployeesRouteWithChildren =
  ProtectedEmployeesRoute._addFileChildren(ProtectedEmployeesRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedCreateEmployeeRoute: typeof ProtectedCreateEmployeeRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedEmployeesRoute: typeof ProtectedEmployeesRouteWithChildren
  ProtectedReportsRoute: typeof ProtectedReportsRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedCreateEmployeeRoute: ProtectedCreateEmployeeRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedEmployeesRoute: ProtectedEmployeesRouteWithChildren,
  ProtectedReportsRoute: ProtectedReportsRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicCustomersCustomerIdRouteChildren {
  PublicCustomersCustomerIdEditRoute: typeof PublicCustomersCustomerIdEditRoute
}

const PublicCustomersCustomerIdRouteChildren: PublicCustomersCustomerIdRouteChildren =
  {
    PublicCustomersCustomerIdEditRoute: PublicCustomersCustomerIdEditRoute,
  }

const PublicCustomersCustomerIdRouteWithChildren =
  PublicCustomersCustomerIdRoute._addFileChildren(
    PublicCustomersCustomerIdRouteChildren,
  )

interface PublicCustomersRouteChildren {
  PublicCustomersCustomerIdRoute: typeof PublicCustomersCustomerIdRouteWithChildren
}

const PublicCustomersRouteChildren: PublicCustomersRouteChildren = {
  PublicCustomersCustomerIdRoute: PublicCustomersCustomerIdRouteWithChildren,
}

const PublicCustomersRouteWithChildren = PublicCustomersRoute._addFileChildren(
  PublicCustomersRouteChildren,
)

interface PublicTasksTaskIdRouteChildren {
  PublicTasksTaskIdEditRoute: typeof PublicTasksTaskIdEditRoute
}

const PublicTasksTaskIdRouteChildren: PublicTasksTaskIdRouteChildren = {
  PublicTasksTaskIdEditRoute: PublicTasksTaskIdEditRoute,
}

const PublicTasksTaskIdRouteWithChildren =
  PublicTasksTaskIdRoute._addFileChildren(PublicTasksTaskIdRouteChildren)

interface PublicTasksRouteChildren {
  PublicTasksTaskIdRoute: typeof PublicTasksTaskIdRouteWithChildren
}

const PublicTasksRouteChildren: PublicTasksRouteChildren = {
  PublicTasksTaskIdRoute: PublicTasksTaskIdRouteWithChildren,
}

const PublicTasksRouteWithChildren = PublicTasksRoute._addFileChildren(
  PublicTasksRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicCreateCustomerRoute: typeof PublicCreateCustomerRoute
  PublicCreateTaskRoute: typeof PublicCreateTaskRoute
  PublicCustomersRoute: typeof PublicCustomersRouteWithChildren
  PublicSigninRoute: typeof PublicSigninRoute
  PublicSignupRoute: typeof PublicSignupRoute
  PublicTasksRoute: typeof PublicTasksRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicCreateCustomerRoute: PublicCreateCustomerRoute,
  PublicCreateTaskRoute: PublicCreateTaskRoute,
  PublicCustomersRoute: PublicCustomersRouteWithChildren,
  PublicSigninRoute: PublicSigninRoute,
  PublicSignupRoute: PublicSignupRoute,
  PublicTasksRoute: PublicTasksRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
